include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    invalid_assignment: error
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_empty_else: true
    always_use_package_imports: true
    require_trailing_commas: true
    unawaited_futures: true
